# Desenvolvimento de Pacotes Científicos com Python

**por**: Rafael Pereira da Silva

# PARTE 2
# Seção 1: Numpy
O Numpy é uma biblioteca python que permite construir *arrays multidimensionais*. As operações com Numpy costumam ser mais rápidas em comparação a outras estruturas Python, pois 30% da biblioteca é escrita em C, além de outros aspectos.

## 1.1 - Arrays 

<br/>

#### Sintaxe

<br/>


```python
>>> import numpy as np
>>> arr = np.array([1, 2, 3, 4, 5]) # array 1d
```

<br/>

#### Algums atributos de arrays

<br/>

| Atributos | Retorna  | Descrição |
| :-- | :-- | :-- |
| ndarray.ndim | int |  número de dimensões (axes) |
| ndarray.shape |  tupla |  quantidade de dados em cada dimensão |
| ndarray.size | int | número de elementos |
| ndarray.dtype| dtype | tipo das variáveis dos elementos |

<br/>

**nota:**
<pre>O np.array(iterável) é uma função e não o objeto, mas retorna o objeto ndarray. </pre>
<pre>Podemos criar arrays de quantas dimensões forem necessárias.  </pre>

In [1]:
import numpy as np

## 1.2 - Funções matemáticas

<br/>

O Numpy possui uma série de funções matemáticas e constantes implementadas, de forma muito similar a biblioteca math, que é built-in do python.

<br/>

### Funções

<br/>

#### Trigonométricas

| Função |  Descrição |
| :-- | :-- |
| sin(x) | seno |
| cos(x) | cosseno |
| tan(x) | tangente |
| arcsin(x) | arco seno |
| arccos(x) | arco cosseno |
| arctan(x) | arco tangente |
| sinh(x) | seno hiperbólico |

<br/>

#### Exponencial e logarítimos

| Função |  Descrição |
| :-- | :-- |
| exp(x) | exponencial |
| log(x) | logarítimo natural |
| log10(x) | logarítimo na base 10 |
| sqrt(x) | raiz quadrada |

<br/>

#### constantes
| Constante |  Descrição |
| :-- | :-- |
| np.pi | $\pi$ = 3.141592... |
| np.e | $e$ = 2.7182... |
| np.nan | representação em float de valor não numérico (not a number) |
| np.inf | representação em float de valor infinito |

<br/>

**nota:**
<pre>https://numpy.org/doc/stable/reference/routines.math.html</pre>

In [1]:
import numpy as np

In [2]:
np.e

2.718281828459045

## 1.3 - Criação de arrays

<br/>

#### Funções para criação de arrays

| Função | Descrição |
| :-- | :-- |
| np.zeros(shape) | array preenchido com zeros |
| np.ones(shape) | array preenchido com uns |
| np.eye(dimensão) | matriz identidade |
| np.arange(início, fim, passo) | cria um array unidimensioanl |
| np.linspace(início, fim, quantidade) | cria um array unidimensioanl |
| np.vstack([*arrays*]) e hstack([*arrays*]) | adiciona elementos de um ou mais arrays |

<br/>

#### Métodos para dimensionar os arrays:
 
 | Método | Descrição |
| :-- | :-- |
|reshape(novo_shape) | retorna um array com o shape indicado|
|resize(novo_shape) | modifica o shape do array em que está sendo aplicado|


**nota**
<pre>Preste atenção em quais métodos modificam o array e quais retornam um array novo </pre>
<pre>Arrays não possuem tamanho dinâmico como as listas. Mas podemos "roubar" e modificar o tamanho de um array empilhando eles (um novo objeto será gerado). </pre>

In [7]:
arr = np.linspace(1, 10, 10)

In [11]:
arr.resize(2, 5)

## 1.4 - Operações básicas com arrays

<br/>

Os arrays numpy possuem muitas (MUITAS) funcionalidades. Eles podem se comportar como simples estruturas de dados, como vetores ou mesmo matrizes, depende de como nós os manipulamos. Nessa aula iremos ver as operações básicas, aquelas que fazem os arrays se comportarem como estrutura de dados.

<br/>

**Operações básicas e como elas se comportam**
- Arrays aceitam operações básicas $+$, $-$, $\times$, $\div$ e eles a executam elemento a elemento, por isso os arrays devem ter exatamente o mesmo shape.
- Arrays aceitam as operações básicas entre um array e um número (float ou int). Ele executará a operação entre o número e cada elemento do array.
- Operações booleanas também são aceitas e retornam um array preenchido com booleanos.

<br/>

**nota**
<pre>Mais para frente iremos ver operações vetoriais e matriciais com arrays. </pre>


In [13]:
import numpy as np

In [31]:
arr_1 = np.linspace(1, 10, 10).reshape(2, 5)
arr_2 = np.linspace(1, 100, 10).reshape(2, 5)


In [33]:
8 * arr_1

array([[ 8., 16., 24., 32., 40.],
       [48., 56., 64., 72., 80.]])

In [57]:
a = np.array([1, 2, 3])
b = np.array([1, 5, 3])

a == b

array([ True, False,  True])

## 1.5 - Gerenciamento de memória do numpy

<br/>

Lembrem-se que o array numpy não é dinâmico. Além disso, tome cuidado com os objetos quando for copiar, manipular e colar.

<br/>

#### Copiar um array
| Método | Descrição |
| :-- | :-- |
| .copy() | faz a cópia (deep copy) do array. Cuidado! O sinal de igual não executa essa função |

<br/>

#### Propriedade
| Método | Descrição |
| :-- | :-- |
| .base | Retorna o array de base que foi utilizado para criar o array atual |

<br/>

**nota**
<pre>Podemos utilizar o operador lógico is para checar se temos um novo ojeto. </pre>

In [1]:
import numpy as np

In [4]:
np.may_share_memory

<function numpy.may_share_memory>

In [8]:
arr_1 = np.linspace(1, 10 , 10)

In [10]:
arr_1.reshape(2, 5)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [11]:
arr_1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
arr_2 = arr_1.reshape(2, 5)

In [19]:
hex(id(arr_2.base))

'0x1c75f8ecb70'

In [20]:
hex(id(arr_1))

'0x1c75f8ecc30'

In [21]:
np.may_share_memory(arr_1, arr_2)

True

In [27]:
arr_1.nbytes

80

## 1.6 Métodos estatísticos para arrays

<br/>


| Método | Descrição |
| :-- | :-- |
| max(axis=None) | Retorna o valor máximo  |
| mix(axis=None) | Retorna o valor mínimo  |
| argmax(axis=None) | Retorna o índice de valo  |
| argmin(axis=None) | Retorna o índice de valor mínimo  |
| sum(axis=None) | Retorna a soma dos elementos do array|
| cumsum(axis=None) | Retorna um array com a soma acumulada dos valores |
| prod(axis=None) | Retorna o produto dos elementos do array |
| cumprod(axis=None) | Retorna o produto acumulado dos elementos do array |
| mean(axis=None) | Retorna a média dos elementos do array |
| var(axis=None) | Retorna a variância do array |
| std(axis=None) | Retorna o desvio padrão do array |

<br/>

**nota**
<pre>Quando a opção axis é utilizada, nós executamos a operação no eixo especificado. </pre>

In [37]:
arr_1.cumsum()

array([ 1.,  3.,  6., 10., 15., 21., 28., 36., 45., 55.])

## 1.7 Índices e fatias de arrays (Indexing and slicing)

De maneira similar a que fizemos em listas, podemos fatiar arrays.

<br/>

| Sintaxe | Descrição |
| :-- | :-- |
| [i] | para 1 dimensão funciona como nas listas |
| [:i] | exibe um array que vai do índice 0 até o anterior ao i|
| [i:] | exibe um array que vai do índice posterior ao i até o último índice|
|[::i] | exibe todos os elementos variando de i em i |
| [::-i] | exibe a sequência de elementos de trás pra frente variando de i em i |
| [a:b:c] | início, fim, step |
| [i,j] | para exibir um elemento de uma matriz |
| [i,a:b] | retorna uma fatia da linha i com elementos das colunas de a até b |
| [n,i,j] | outra dimensão, linha, coluna |

<br/>

**nota**
<pre>Existem operações mais sofisticadas para o slicing, conhecidas como fancy index.</pre>

## 1.8 - Matrizes no Numpy
Os arrays numpy podem ser interpretados diretamente como matrizes. Para isso, precisamos utilizar as funções certas!

<br/>

#### Propriedades
| Propriedades | Descrição |
| :-- | :-- |
| .T | Matriz transposta |


<br/>

#### Funções

| Funções | Descrição |
| :-- | :-- |
| np.transpose(A) | Retorna a matriz transposta de A |
| np.linalg.det(A) | Retorna o determinante da matriz A |
| np.matmul(A, B) ou @ | Retorna a multiplicação matricial entre A e B. |


**nota**
<pre>O linalg é um pacote a parte do numpy. Ele possui muitas funcionalidades que iremos explorar no capítulo de scipy. </pre>

<pre>O numpy também tem um objeto np.matrix, que nos permite fazer os tratamentos matriciais de uma forma mais simples. Eu particularmente dou preferência por usar os arrays. </pre>

In [1]:
import numpy as np

In [4]:
a = np.linspace(1, 10, 10).reshape(2, 5)
b = np.linspace(11, 20, 10).reshape(5, 2)

In [54]:
e = np.linspace(1, 1.5, 9).reshape(3, 3)

In [55]:
d

array([[1.    , 1.0625, 1.125 ],
       [1.1875, 1.25  , 1.3125],
       [1.375 , 1.4375, 1.5   ]])

In [56]:
np.linalg.det(e)

0.0

In [19]:
np.cross(a, b)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [14]:
b.transpose()

array([[11., 13., 15., 17., 19.],
       [12., 14., 16., 18., 20.]])

In [16]:
b.T

array([[11., 13., 15., 17., 19.],
       [12., 14., 16., 18., 20.]])

In [30]:
c = np.linspace(1, 3, 3)

In [31]:
np.cross(c, c)

array([0., 0., 0.])

## 1.9 - Vetores

<br/>

#### Funções
| Funções | Descrição |
| :-- | :-- |
| np.cross(a, b) | Produto vetorial (o array precisa ser um vetor com 2 ou 3 elementos) |
| np.dot(a, b) ou @ | Produto escalar |
| np.linalg.norm(a) | Retorna a norma de a |

<br/>

#### Produto vetorial (cross product)
É um produto com dois vetores, onde o resultado é um terceiro vetor ortogonal aos outros dois.

$$ \vec{a} \times \vec{b} = | a |.| b |. sin(\theta).\vec{n}  =  \begin{bmatrix}
   \vec{i} & \vec{j} & \vec{k} \\
   a_x & a_y & a_z \\
   b_x & b_y & b_z
  \end{bmatrix} $$

<br/>

#### Produto escalar (dot product / scalar product)
O produto escalar entre dois vetores fornece um número real. Geometricamente o produto escalar fornece a projeção de $\vec{a}$ em $\vec{b}$ se este último tiver comprimento unitário.

$$ \vec{a} . \vec{b} = (a_x.b_x + a_y.b_y + a_z.b_z) =  | a |.| b |. cos(\theta)$$

<br/>

<pre>O linalg é um pacote a parte do numpy. Ele possui outras funcionalidades que iremos explorar no capítulo de scipy. </pre>

In [36]:
np.matmul(c, c)

14.0

# Exercícios

## E1.1 - 
Crie uma matrix $2 \times  2$ totalmente preenchida com $\pi$.

In [5]:
import numpy as np

m = np.array([[np.pi, np.pi],
              [np.pi, np.pi]])

In [6]:
m

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

## E1.2 - 
Crie uma matrix $10 \times  10$ totalmente preenchida com $\pi$.

In [11]:
m = np.ones(100).reshape(10, 10) * np.pi
m

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.1415926

## E1.3 - 
Crie uma matrix $2 \times  10$ onde ambas as linhas contém arrays com números inteiros indo de 1 a 10.

Mude o último número da matriz de 10 para 100.

In [12]:
import numpy as np

In [32]:
a = np.arange(1, 11, 1)

b = np.vstack([a, a])

In [33]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [37]:
b[1, 9] = 100

In [38]:
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9, 100]])

## E1.4 - 
Dado um array de números inteiros indo de 0 a 100, retorne o desvio padrão e a variância deste array.

In [39]:
import numpy as np

In [45]:
a = np.arange(0, 101, 1)
a.min()

0

## E1.5 - 
Gere uma matriz $ 3 \times 10 $ com números aleatórios. Depois extraia um array com os três últimos números da segunda linha.

<br/>

Dica:

Use a função abaixo para gerar um array com números aleatórios
```python
>>> np.random.rand(3, 10)
```

In [46]:
import numpy as np

In [47]:
m = np.random.rand(3, 10)
m

array([[0.32470555, 0.43836869, 0.76355356, 0.11373676, 0.15918102,
        0.80368824, 0.61012429, 0.28376739, 0.30488679, 0.1910903 ],
       [0.68835688, 0.9508969 , 0.67019275, 0.52330445, 0.61895698,
        0.63219067, 0.55123872, 0.26562141, 0.5501472 , 0.70420808],
       [0.93357046, 0.01908056, 0.53493673, 0.70948041, 0.3311262 ,
        0.37121507, 0.14426469, 0.44893492, 0.56031485, 0.87626918]])

In [58]:
m[1, 7::]

array([0.26562141, 0.5501472 , 0.70420808])